### ISSUE TITLE
Shoutbox

### ISSUE THREAD

**Issue by voneiden** [voneiden/voneiden#1]
What's this now, MyGitSpace?

**Comment by voneiden** [comment]
![monad_000](https://user-images.githubusercontent.com/437576/177875855-2602a25b-b1b0-48e9-bddb-23669ffcac0f.png)

**Comment by voneiden** [comment]
OIJDSAOJDSAOIJSADOIDSAOIJDSA

**Comment by Raekkeri** [comment]
_**The need to be observed and understood was once satisfied by God. Now we can implement the same functionality with data-mining algorithms.**_
